### ISSUE TITLE
[GB Studio 2 Beta] Actor: Set Direction in a Timer Script causes player to zoom off screen

### ISSUE THREAD

**Issue by patrickmollohan** [chrismaltby/gb-studio#449]
**Describe the bug**
I recently created a custom script in GB Studio 1.2.1 that creates a strafe effect when the player holds the "B" button. It works fairly decently, save for the sprite flickering when it switches between sprite sheets. However, this no longer functions in the v2 beta, as pressing left or right on the D-Pad causes the player sprite to zoom off screen in one direction infinitely.

**To Reproduce**
Extract and load "Strafe v1.2.1" in GB Studio v1.2.1.
Run the game. Face the direction you want to strafe. Hold the "B" button (default "X" on the keyboard) to strafe. Move around randomly, let go of the "B" button. Player should face the direction that was last faced before holding the "B" button.
Extract and load "Strafe v2 Beta" in GB Studio 2 Beta.
Run the game. Face the direction you want to strafe. Hold the "B" button (default "X" on the keyboard) to strafe. Move around randomly, let go of the "B" button. Player zooms off in the distance.

**Expected behavior**
The player should "strafe". It doesn't look correct since the direction the player faces gets overwritten by the d-pad presses, but with additional sprite sheets which I didn't include, you can hide this with two-frame sheets for the up/down/left/right directions. That behaviour is normal. Once you let go of the "B" button, the player sprite should face the direction you locked in before pressing the "B" button.

**Screenshots**
N/A

**Platform (please complete the following information):**
 - OS: Ubuntu 19.04
 - App version 1.2.1 (working), 2 beta (not working)

**Additional context**
Since Github displays "Something went really wrong, and we can't process that file." on my zip archives, the project files can be downloaded from here: https://ufile.io/rrme06ka

**Comment by chrismaltby** [comment]
I've just merged that update @patrickmollohan I just had to remove the `|| (actors[(i)].pos.y == 254)` part as that's left over from the smaller scene sizes in v1. I'm not seeing the issue now

**Comment by coasterspaul** [comment]
That's also fixed my player zooming off thanks to a Set Direction in a joypad-attached script. However, now I'm not seeing the direction change at all unless the player's at a standstill. That's definitely better, but it might still have a few unexpected effects. (Something I was trying to do with attacks that was broken because of this is now broken in an interesting new way!... which is why I'm suggesting it as a proper feature.)
